variable "ad1_name" {}
variable "compartment_ocid" {}
variable "prefix" {}
variable "uid" {}
variable "image_ocid" {}
variable "InstanceShape" {}
variable "subnet_ocid" {}
variable "sshKey" {}
variable "chefautomate_public_ip" {}
variable "ssh_private_key" {}